blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'blog'

urlpatterns = [
    path('comment/<int:pk>/', views.CreateComment.as_view(), name="create_comment"),
    path('<slug:slug>/<slug:post_slug>/',
         views.PostDetailView.as_view(), name="post_single"),
    path('<slug:slug>/', views.PostListView.as_view(), name="post_list"),
    # path('', cache_page(60 * 15)(views.HomeView.as_view()), name="home"),
    path('', views.HomeView.as_view(), name="home"),
]

config/urls.py
"""cook URL Configuration
"""
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('auth/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py

from django.urls import path
from django.contrib.auth import views as authViews

from .views import registration_view, LoginView


app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', registration_view, name='signup'),
    path('logout/', authViews.LogoutView.as_view(next_page='/'), name='logout'),
]

blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from mptt.models import MPTTModel, TreeForeignKey

User = get_user_model()


class Category(MPTTModel):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    parent = TreeForeignKey(
        'self',
        related_name="children",
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = 'категорию'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'тег'
        verbose_name_plural = 'Теги'


class Post(models.Model):
    author = models.ForeignKey(
        User, related_name="posts", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='articles/')
    text = models.TextField()
    category = models.ForeignKey(
        Category,
        related_name="posts",
        on_delete=models.SET_NULL,
        null=True
    )
    tags = models.ManyToManyField(Tag, related_name="post")
    create_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_single', args=[self.category.slug, self.slug])

    def get_recipes(self):
        return self.recipes.all()

    def get_comments(self):
        return self.comment.all()

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'Посты'


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    serves = models.CharField(max_length=50)
    prep_time = models.PositiveIntegerField(default=0)
    cook_time = models.PositiveIntegerField(default=0)
    ingredients = RichTextField()
    directions = RichTextField()
    post = models.ForeignKey(
        Post,
        related_name="recipes",
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'рецепт'
        verbose_name_plural = 'Рецепты'


class Comment(models.Model):
    author = models.ForeignKey(
        User,
        related_name="comments",
        on_delete=models.CASCADE,
        verbose_name="автор"
    )
    message = models.TextField(
        max_length=500,
        blank=False,
        verbose_name="сообщение"
    )
    created_at = models.DateTimeField(
        default=timezone.now,
        verbose_name="дата создания"
    )
    post = models.ForeignKey(
        Post,
        related_name="comments",
        on_delete=models.CASCADE,
        verbose_name="пост"
    )

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-created_at']  # новые комментарии сверху

    def __str__(self):
        return f"Комментарий от {self.author.username} ({self.created_at})"

blog/forms.py
from django import forms
from django.utils.html import escape
from .models import Comment  # Импорт модели, а не формы


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']
        widgets = {
            'message': forms.Textarea(attrs={
                'placeholder': 'Ваш комментарий...',
                'rows': 4,
                'class': 'form-control',
            }),
        }

    def clean_message(self):
        message = self.cleaned_data.get('message')
        if not message:
            raise forms.ValidationError("Комментарий не может быть пустым.")
        escaped_message = escape(message.strip())
        return escaped_message

blog/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Post, Comment
from .forms import CommentForm


class HomeView(ListView):
    model = Post
    paginate_by = 9
    template_name = "blog/home.html"


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs.get("slug")).select_related('category')


class PostDetailView(DetailView):
    model = Post
    context_object_name = "post"
    slug_url_kwarg = 'post_slug'

    def get_object(self, queryset=None):
        return Post.objects.get(
            category__slug=self.kwargs['slug'],
            slug=self.kwargs['post_slug']
        )


class CreateComment(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/post_detail.html'  # Укажите ваш шаблон

    def form_valid(self, form):
        form.instance.author = self.request.user  # Автор = текущий пользователь
        form.instance.post_id = self.kwargs.get('pk')  # Привязка к посту
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:post_single', kwargs={
            'slug': self.object.post.category.slug,
            'post_slug': self.object.post.slug
        })

templates/blog/include/sidebar.html
{% load social_tags cache %}


{% cache 5000 sidebar %}
<div class="col-lg-4 col-md-4">
  <div class="sidebar__item">
    <div class="sidebar__about__item">
      <div class="sidebar__item__title">
        <h6>Обо мне</h6>
      </div>
      {% get_about as about %}
      <img src="{{ about.get_first_image }}" alt="">
      <h6>Приветствую на своём сайте, я автор данного сайта, на котором будут публиковаться различные рецепты и новости из кулинарного мира... <span>{{ about.name }}</span></h6>
      <p>{{ about.mini_text|safe }}</p>
      <a href="{% url 'about' %}" class="primary-btn">Читать далее</a>
    </div>
    <div class="sidebar__follow__item">
      <div class="sidebar__item__title">
        <h5>Подписывайтесь чтобы следить за новостями</h5>
      </div>
      {% get_social_links as social_links %}
      <div class="sidebar__item__follow__links">
        {% for item in social_links %}
          <a href="{{ item.link }}"><img src="{{ item.icon.url }}"></a>
        {% endfor %}
      </div>
    </div>
    <div class="sidebar__item__banner">
      <img src="/static/img/sidebar/banner.jpg" alt="">
    </div>
    <div class="sidebar__item__categories">
      <div class="sidebar__item__title">
        <h6>Категории</h6>
      </div>
    {% include './sidebar_category.html' %}

    </div>
    <div class="sidebar__subscribe__item">
      <div class="sidebar__item__title">
        <h6>Подписывайтесь</h6>
      </div>
      <p>Подпишитесь на нашу рассылку и получайте наши самые свежие обновления прямо на свой почтовый ящик!</p>
      <form action="#">
        <input type="text" class="email-input" placeholder="Ваша электронная почта">
        <label for="s-agree-check">
          Я согласен с условиями
          <input type="checkbox" id="s-agree-check">
          <span class="checkmark"></span>
        </label>
        <button type="submit" class="site-btn">Подписаться</button>
      </form>
    </div>
  </div>
</div>
{% endcache %}

templates/blog/include/sidebar_category.html
{% load menu_tags %}
<ul>
  {% get_list_category as list_category %}
  {% for node in list_category %}
  <li><a href="{% url 'blog:post_list' node.slug %}">{{ node.name }}</a></li>
  {% endfor %}
</ul>

templates/blog/include/top_nav.html
{% load menu_tags cache %}

{% cache 5000 top_nav %}
<nav class="header__menu">
  <ul>
    <li class="active"><a href="{% url 'blog:home' %}">Главная</a></li>
    {% get_last_posts %}
    {% get_categories %}
    <li><a href="{% url 'about' %}">О нас</a></li>
    <li><a href="{% url 'users:signup' %}">Зарегистрироваться</a></li>
    <li><a href="{% url 'users:login' %}">Войти</a></li>
  </ul>
</nav>
{% endcache %}