blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'blog'

urlpatterns = [
    path('comment/<int:pk>/', views.CreateComment.as_view(), name="create_comment"),
    path('<slug:slug>/<slug:post_slug>/',
         views.PostDetailView.as_view(), name="post_single"),
    path('<slug:slug>/', views.PostListView.as_view(), name="post_list"),
    # path('', cache_page(60 * 15)(views.HomeView.as_view()), name="home"),
    path('', views.HomeView.as_view(), name="home"),
]

config/urls.py
"""cook URL Configuration
"""
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('auth/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py

from django.urls import path
from django.contrib.auth import views as authViews

from .views import registration_view, LoginView


app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', registration_view, name='signup'),
    path('logout/', authViews.LogoutView.as_view(next_page='/'), name='logout'),
]

blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from mptt.models import MPTTModel, TreeForeignKey

User = get_user_model()


class Category(MPTTModel):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    parent = TreeForeignKey(
        'self',
        related_name="children",
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = 'категорию'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'тег'
        verbose_name_plural = 'Теги'


class Post(models.Model):
    author = models.ForeignKey(
        User, related_name="posts", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='articles/')
    text = models.TextField()
    category = models.ForeignKey(
        Category,
        related_name="posts",
        on_delete=models.SET_NULL,
        null=True
    )
    tags = models.ManyToManyField(Tag, related_name="post")
    create_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_single', args=[self.category.slug, self.slug])

    def get_recipes(self):
        return self.recipes.all()

    def get_comments(self):
        return self.comment.all()

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'Посты'


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    serves = models.CharField(max_length=50)
    prep_time = models.PositiveIntegerField(default=0)
    cook_time = models.PositiveIntegerField(default=0)
    ingredients = RichTextField()
    directions = RichTextField()
    post = models.ForeignKey(
        Post,
        related_name="recipes",
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'рецепт'
        verbose_name_plural = 'Рецепты'


class Comment(models.Model):
    author = models.ForeignKey(
        User,
        related_name="comments",
        on_delete=models.CASCADE,
        verbose_name="автор"
    )
    message = models.TextField(
        max_length=500,
        blank=False,
        verbose_name="сообщение"
    )
    created_at = models.DateTimeField(
        default=timezone.now,
        verbose_name="дата создания"
    )
    post = models.ForeignKey(
        Post,
        related_name="comments",
        on_delete=models.CASCADE,
        verbose_name="пост"
    )

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-created_at']  # новые комментарии сверху

    def __str__(self):
        return f"Комментарий от {self.author.username} ({self.created_at})"

blog/forms.py
from django import forms
from django.utils.html import escape
from .models import Comment  # Импорт модели, а не формы


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']
        widgets = {
            'message': forms.Textarea(attrs={
                'placeholder': 'Ваш комментарий...',
                'rows': 4,
                'class': 'form-control',
            }),
        }

    def clean_message(self):
        message = self.cleaned_data.get('message')
        if not message:
            raise forms.ValidationError("Комментарий не может быть пустым.")
        escaped_message = escape(message.strip())
        return escaped_message

blog/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Post, Comment
from .forms import CommentForm


class HomeView(ListView):
    model = Post
    paginate_by = 9
    template_name = "blog/home.html"


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs.get("slug")).select_related('category')


class PostDetailView(DetailView):
    model = Post
    context_object_name = "post"
    slug_url_kwarg = 'post_slug'

    def get_object(self, queryset=None):
        return Post.objects.get(
            category__slug=self.kwargs['slug'],
            slug=self.kwargs['post_slug']
        )


class CreateComment(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/post_detail.html'  # Укажите ваш шаблон

    def form_valid(self, form):
        form.instance.author = self.request.user  # Автор = текущий пользователь
        form.instance.post_id = self.kwargs.get('pk')  # Привязка к посту
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:post_single', kwargs={
            'slug': self.object.post.category.slug,
            'post_slug': self.object.post.slug
        })

templates/blog/home.html
{% extends 'base.html' %}


{% block content %}
  <!-- Hero Section Begin -->

  <!-- Categories Section Begin -->
  <section class="categories spad">
{#    <div class="container">#}
{#      <div class="row">#}
{#        <div class="col-lg-3 col-md-6 col-sm-6">#}
{#          <div class="categories__item set-bg" data-setbg="img/categories/cat-1.jpg">#}
{#            <div class="categories__hover__text">#}
<!-- {#              <h5>Обеды</h5>#}
{#              <p>3 статьи</p>#} -->
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#        <div class="col-lg-3 col-md-6 col-sm-6">#}
{#          <div class="categories__item set-bg" data-setbg="img/categories/cat-2.jpg">#}
{#            <div class="categories__hover__text">#}
<!-- {#              <h5>Обеды</h5>#}
{#              <p>3 статьи</p>#} -->
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#        <div class="col-lg-3 col-md-6 col-sm-6">#}
{#          <div class="categories__item set-bg" data-setbg="img/categories/cat-3.jpg">#}
{#            <div class="categories__hover__text">#}
<!-- {#              <h5>Обеды</h5>#}
{#              <p>3 статьи</p>#} -->
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#        <div class="col-lg-3 col-md-6 col-sm-6">#}
{#          <div class="categories__item set-bg" data-setbg="img/categories/cat-4.jpg">#}
{#            <div class="categories__hover__text">#}
<!-- {#              <h5>Обеды</h5>#}
{#              <p>3 статьи</p>#} -->
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}
    <div class="categories__post">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-8">
            {% for post in post_list %}
                {% if forloop.first %}
                  <div class="categories__post__item categories__post__item--large">
                    <div class="categories__post__item__pic set-bg"
                         data-setbg="{{ post.image.url }}">
                      <div class="post__meta">
                        <h4>{{ post.create_at|date:"d" }}</h4>
                        <span>{{ post.create_at|date:"M" }}</span>
                      </div>
                    </div>
                    <div class="categories__post__item__text">
                      <ul class="post__label--large">
                        <li>{{ post.category }}</li>
                      </ul>
                      <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                      <ul class="post__widget">
                        <li>by <span>{{ post.author }}</span></li>
                        <!-- <li>3 минуты чтения</li>
                        <li>2 комментария</li> -->
                      </ul>
                      <p>{{ post.text|slice:":250" }}</p>
                      <a href="{{ post.get_absolute_url }}" class="primary-btn">Читать далее</a>
                    </div>
                  </div>
                  <div class="row">
                {% endif %}
            {% endfor %}
                <div class="col-lg-6 col-md-6 col-sm-6">
                  {% for post in post_list %}
                      {% if forloop.counter <= 5 and  forloop.counter > 1 %}
                        <div class="categories__post__item">
                          <div class="categories__post__item__pic small__item set-bg"
                               data-setbg="{{ post.image.url }}">
                            <div class="post__meta">
                              <h4>{{ post.create_at|date:"d" }}</h4>
                              <span>{{ post.create_at|date:"M" }}</span>
                            </div>
                          </div>
                          <div class="categories__post__item__text">
                            <span class="post__label">{{ post.category }}</span>
                            <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                            <ul class="post__widget">
                              <li>Автор <span>{{ post.author }}</span></li>
                              <!-- <li>5 минут чтения</li>
                              <li>6 комментариев</li> -->
                            </ul>
                            <p>{{ post.text|slice:":250" }}</p>
                          </div>
                        </div>
                      {% endif %}
                  {% endfor %}
                </div>

                <div class="col-lg-6 col-md-6 col-sm-6">
                  {% for post in post_list %}
                    {% if forloop.counter > 5 %}
                      <div class="categories__post__item">
                        <div class="categories__post__item__pic small__item set-bg"
                             data-setbg="{{ post.image.url }}">
                          <div class="post__meta">
                            <h4>{{ post.create_at|date:"d" }}</h4>
                            <span>{{ post.create_at|date:"M" }}</span>
                          </div>
                        </div>
                        <div class="categories__post__item__text">
                          <span class="post__label">{{ post.category }}</span>
                          <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                          <ul class="post__widget">
                            <li>Автор <span>{{ post.author }}</span></li>
                            <!-- <li>2 минуты чтения</li>
                            <li>3 комментария</li> -->
                          </ul>
                          <p>{{ post.text|slice:":250" }}</p>
                        </div>
                      </div>
                    {% endif %}
                  {% endfor %}
                </div>
              </div>


            <div class="col-lg-12 text-center">
              <div class="load__more__btn">
                <a href="#">Загрузить больше</a>
              </div>
            </div>
          </div>
          {% include 'blog/include/sidebar.html' %}
        </div>
      </div>
    </div>
  </section>
  <!-- Categories Section End -->

{% endblock content %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load social_tags %}

{% block content %}
<section class="single-post spad">
  <div class="single-post__hero set-bg" data-setbg="{{ post.image.url }}"></div>
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-8">
        <div class="single-post__title">
          <div class="single-post__title__meta">
            <h2>{{ post.create_at|date:"d" }}</h2>
            <span>{{ post.create_at|date:"M" }}</span>
          </div>
          <div class="single-post__title__text">
            <ul class="label">
              <li>{{ post.category }}</li>
            </ul>
            <h4>{{ post.title }}</h4>
            <ul class="widget">
              <li>by {{ post.author }}</li>
              <!-- <li>3 минуты чтения</li>
                <li>2 комментария</li> -->
            </ul>
          </div>
        </div>
        <div class="single-post__social__item">
          <ul>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
            <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
          </ul>
        </div>
        <div class="single-post__top__text">
          <p>{{ post.text|truncatewords:20 }}</p>
        </div>
        <div class="single-post__recipe__details">
          {% for recipe in post.get_recipes %}
          <div class="single-post__recipe__details__option">
            <ul>
              <li>
                <h5><i class="fa fa-user-o"></i> Порции</h5>
                <span>{{ recipe.serves }}</span>
              </li>
              <li>
                <h5><i class="fa fa-clock-o"></i> Время подготовки</h5>
                <span>{{ recipe.prep_time }}</span>
              </li>
              <li>
                <h5><i class="fa fa-clock-o"></i> Время приготовления</h5>
                <span>{{ recipe.cook_time }}</span>
              </li>
              <li><a href="#" class="primary-btn"><i class="fa fa-print"></i> Читать далее</a></li>
            </ul>
          </div>

          <div class="single-post__recipe__details__indegradients">
            <h5>Ингредиенты</h5>
            {{ recipe.ingredients|safe }}
          </div>
          <div class="single-post__recipe__details__direction">
            <h5>Шаги</h5>
            {{ recipe.directions|safe }}
          </div>
          {% endfor %}
        </div>

        <div class="single-post__desc">
          <p>{{ post.text }}</p>
        </div>
        <div class="single-post__tags">
          {% for tag in post.tags.all %}
          <a href="#">{{ tag.name }}</a>
          {% endfor %}
        </div>
        <div class="single-post__next__previous">
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
              <a href="#" class="single-post__previous">
                <h6><span class="arrow_carrot-left"></span> Предыдущий пост</h6>
                <div class="single-post__previous__meta">
                  <h4>08</h4>
                  <span>Авг</span>
                </div>
                <div class="single-post__previous__text">
                  <span>Dinner</span>
                  <h5>Лучшие виды приготовления мяса, <br /> в конце лета</h5>
                </div>
              </a>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
              <a href="#" class="single-post__next">
                <h6>Следующий пост <span class="arrow_carrot-right"></span></h6>
                <div class="single-post__next__meta">
                  <h4>05</h4>
                  <span>Авг</span>
                </div>
                <div class="single-post__next__text">
                  <span>Торт</span>
                  <h5>Торт который я всегда <br />готовлю к осени.</h5>
                </div>
              </a>
            </div>
          </div>
        </div>
        {% get_about as about %}
        <div class="single-post__author__profile">
          <div class="single-post__author__profile__pic">
            <img src="{{ about.get_first_image }}" alt="">
          </div>
          <div class="single-post__author__profile__text">
            <h4>{{ about.name }}</h4>
            <p>{{ about.mini_text|safe }}</p>
            <div class="single-post__author__profile__social">
              {% get_social_links as social_links %}
              {% for item in social_links %}
              <a href="{{ item.link }}"><img src="{{ item.icon.url }}"></a>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="single-post__comment">
          <div class="widget__title">
            <h4>{{ post.comments.count }} Комментарии</h4> <!-- Используем related_name -->
          </div>
          {% for comment in post.comments.all %}
          <div class="single-post__comment__item">
            <div class="single-post__comment__item__pic">
              <img src="{{ comment.author.profile.image.url|default:'/static/img/default-avatar.jpg' }}"
                alt="{{ comment.author.username }}">
            </div>
            <div class="single-post__comment__item__text">
              <h5>{{ comment.author.username }}</h5>
              <span>{{ comment.created_at|date:"d M Y H:i" }}</span>
              <p>{{ comment.message }}</p>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="single-post__leave__comment">
          <div class="widget__title">
            <h4>Оставьте комментарий</h4>
          </div>
          {% if user.is_authenticated %}
          <form method="post" action="{% url 'blog:create_comment' pk=post.id %}">
            {% csrf_token %}
            <div class="form-group">
              <textarea name="message" class="form-control" rows="5" placeholder="Ваш комментарий..."
                required></textarea>
            </div>
            <button type="submit" class="site-btn">Отправить</button>
          </form>
          {% else %}
          <p>Чтобы оставить комментарий, пожалуйста <a href="{% url 'user:login' %}">войдите</a> или <a
              href="{% url 'user:register' %}">зарегистрируйтесь</a>.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
  <section class="categories categories-grid spad">
    <div class="categories__post">
      <div class="container">
        <div class="categories__grid__post">
          <div class="row">
            <div class="col-lg-8 col-md-8">
              <div class="breadcrumb__text">
                <h2>Categories: <span>{{ post_list.first.category.name }}</span></h2>
                <div class="breadcrumb__option">
                  <a href="#">Главная страница</a>
                  <span>Рецепты</span>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                  {% for post in post_list %}
                    <div class="categories__post__item">
                      <div class="categories__post__item__pic small__item set-bg"
                           data-setbg="{{ post.image.url }}">
                        <div class="post__meta">
                          <h4>{{ post.create_at|date:"d" }}</h4>
                          <span>{{ post.create_at|date:"M" }}</span>
                        </div>
                      </div>
                      <div class="categories__post__item__text">
                        <span class="post__label">{{ post.category }}</span>
                        <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                        <ul class="post__widget">
                          <li>Автор <span>{{ post.author }}</span></li>
                          <!-- <li>3 min read</li>
                          <li>20 Comment</li> -->
                        </ul>
                        <p>{{ post.text|slice:":250" }}</p>
                      </div>
                    </div>
                  {% endfor %}
                </div>
                <div class="col-lg-12 text-center">
                  <div class="load__more__btn">
                    <a href="#">Загрузить больше</a>
                  </div>
                </div>
              </div>
            </div>
            {% include 'blog/include/sidebar.html' %}

          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}